details
git-svn-id: https://scm.gforge.inria.fr/anonscm/svn/simsoc-cert@836 ce709078-17db-4df8-89f4-d3e5bb8270d9

diff --git a/test/extract_file b/test/extract_file
--- a/test/extract_file
+++ b/test/extract_file
@@ -3,13 +3,16 @@
 # SimSoC-Cert, a Coq library on processor architectures for embedded systems.
 # See the COPYRIGHTS and LICENSE files.
 
+# 2010-06-29 Frederic Blanqui
+
 prog=`basename $0`
 
 usage () { echo "usage: $prog [-h] file.v"; }
 
 help () {
   cat <<EOF
-Extract OCaml file for file.v and compile it.
+Generate file.ml from file.v by using Coq extraction mechanism,
+assuming that file.vo exists.
 
 Options:
 -h Provide this help and exit
@@ -25,14 +28,11 @@ esac
 if test $# -ne 1; then args; fi
 
 case $1 in
-*.v) base=${1%.v};;
-*) echo 'error: unknown file type'; exit 1;;
+*.v) ;;
+*) echo 'error: wrong file extension'; exit 1;;
 esac
 
-echo generate Coq file for extracting $base.v ...
-tmp=/tmp/extract_$base.v
+base=`basename $1 .v`
+tmp=/tmp/tmp_$base.v
 echo "Require Extraction $base. Extraction Library $base." > $tmp
-
-echo extract $base.ml ...
-root=..
-coqc -q -R $root/coq SimSoCCert -I $root/arm6 $tmp || exit $?
+coqc -q -R ../coq SimSoCCert -I ../arm6 $tmp
